### ISSUE TITLE
Puddletag 1.1.1-1 not installable on Ubuntu 16.04

### ISSUE THREAD

**Issue by iGadget** [keithgg/puddletag#298] opened 2016-06-09 21:55 UTC
This is the terminal output when I install the suggested packages first and then Puddletag:

igadget@xenial:~/Downloads$ sudo dpkg -i ./puddletag_1.1.1-1_all.deb 
Selecting previously unselected package puddletag.
(Reading database ... 239935 files and directories currently installed.)
Preparing to unpack ./puddletag_1.1.1-1_all.deb ...
Unpacking puddletag (1.1.1) ...
dpkg: dependency problems prevent configuration of puddletag:
 puddletag depends on python-support; however:
  Package python-support is not installed.

dpkg: error processing package puddletag (--install):
 dependency problems - leaving unconfigured
Processing triggers for man-db (2.7.5-1) ...
Processing triggers for bamfdaemon (0.5.3~bzr0+16.04.20160523-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for gnome-menus (3.13.3-6ubuntu3) ...
Processing triggers for desktop-file-utils (0.22-1ubuntu5) ...
Processing triggers for mime-support (3.59ubuntu1) ...
Errors were encountered while processing:
 puddletag

igadget@xenial:~/Downloads$ sudo apt install python-support
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package python-support is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python-support' has no installation candidate

**Comment by keithgg** [comment] 2016-07-08 18:14
Closing. Dupe of #290

**Closed by keithgg** 2016-07-08 18:14 UTC
Labels: bug, Priority-Medium
